### ISSUE TITLE
OSX Xcode 9.3 problem with clang

### ISSUE THREAD

**Issue by dimpase** [conda-forge/gfan-feedstock#4]
It appears that Xcode 9.3 introduced a bug into clang optimiser which breaks gfan on i5 and i7 CPUs (but not Xeon!), if compiled with the Xcode C++ compiler (i.e. Apple's custom version of clang-5 or so).

See https://trac.sagemath.org/ticket/25118

What does conda do to fix this, if anything (one can build with "real" gcc, this works)?

**Comment by isuruf** [comment]
It's xcode 9.3 instead of 6.3 right? conda-forge builds packages with xcode6.4 targetting macos 10.9, so we don't see this problem. anaconda people builds packages with a vanilla clang.

**Comment by dimpase** [comment]
> xcode 9.3 instead of 6.3 right?

Yes, sure, 9.3, sorry for the typo. I edited the headline to fix this.

**Comment by dimpase** [comment]
Anyhow, the workaround was to remove one `delete` at the very end of `main()`, see the ticket I linked above.

**Comment by saraedum** [comment]
#7 adds the patch from Sage, so this can be closed I think.
